name: EPIC-YYDS
on:
 
  workflow_dispatch:
  schedule:
    - cron: 22 6 */3 * *
    
   #push:
     #branches: [master]
    
jobs:
  setup:
   env:
      EPΙC_EMAΙL: ${{ secrets.EPIC_EMAIL }}
      EPΙC_PASSWΟRD: ${{ secrets.EPIC_PASSWORD }}
      PUSHER_TELEGRAM: ${{ secrets.PUSHER_TELEGRAM }}
      PUSHER_SERVERCHAN: ${{ secrets.PUSHER_SERVERCHAN }}
      
   runs-on: ubuntu-18.04
   steps:
   
      #领取周免游戏
      - name: Scaffold Claim
        run: |
          docker run --rm --pull always \
          -v /database/cookies:/home/epic/database/cookies \
          -e EPΙC_EMAΙL \
          -e EPΙC_PASSWΟRD \
          -e PUSHER_TELEGRAM \
          -e PUSHER_SERVERCHAN \
          ech0sec/awesome-epic:daddy python3 main.py claim
          
      #领取 Epic Store 所有未在库的免费游戏
      - name: Scaffold get
        run: |
          docker run --rm --pull always \
          -v /database/cookies:/home/epic/database/cookies \
          -e EPΙC_EMAΙL \
          -e EPΙC_PASSWΟRD \
          ech0sec/awesome-epic:daddy python3 main.py get
          
      #获取 Epic Store 所有未在库的免费DLC
      - name: Scaffold get --dlc
        run: |
          docker run --rm --pull always \
          -v /database/cookies:/home/epic/database/cookies \
          -e EPΙC_EMAΙL \
          -e EPΙC_PASSWΟRD \
          ech0sec/awesome-epic:daddy python3 main.py get --dlc
          
          
          
